### PR TITLE
Hacktoberfest

### PR DESCRIPTION
**Pull request by ghost**
Hacktoberfest

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Mark this as with the invalid tag please. @Bucceroni has been spamming everywhere with these BS PRs.

**Review by robbyoconnor — CHANGES_REQUESTED** [review]
Wow... please stop. Make a meaningful contribution for ONCE. EVERY one of your PRs just makes you look bad.

**Comment by robbyoconnor** [comment]
I have also reported @Bucceroni to GitHub -- here's to hoping they respond soon. This guy needs to go away.

**Comment by doficia** [comment]
Thank you @robbyoconnor.

**Pull request closed without merging**
