### PR TITLE
Jason's mask sprite

### PR DESCRIPTION
**Pull request by Laxaor**
Added Jason's hokey mask from movie Friday 13th. #182

### CODE REVIEW

**Comment by doficia** [comment]
Wow. Jaws dropped.

Are you doing pixel art professionally by any chance? :smile:

**Comment by Laxaor** [comment]
Well this is embarrassing, I'm actually a computer engineer. I do know my way 
 a bit around photoshop and I've read a lot on tutorials on pixel art, but these are the first drawings I post anywhere 😅

I saw your project and just thought it would be simpler to learn the ropes of git by dealing with images instead of code, and that it'd be a great way of practising my pixel art skills all in one shot.

I'm very glad you like my sprites so much that you'd suggest that! 😀

**Comment by doficia** [comment]
I totally had the impression that you had at least a few thousand hours worth of practice. :smile: In that case, you are very talented. ^^

I have also been reading a few pixel art tutorials. Do you have any that you would strongly recommend?

**Comment by Laxaor** [comment]
Maybe you know it already, but I have learned a lot from the animated tutorials by Pedro Medeiros that can be found on [his Patreon](https://www.patreon.com/saint11) (all tutorials are free for everyone to see despite being on there). 

The coolest part is that they are all animated gifs, which makes it easier to understand and visualize some concepts. He also has great examples on how to make sprite animations!

**Comment by doficia** [comment]
Oh boy, when I first stumbled upon that series it was already like 1 AM. I hated myself the next day at work. But now that you have reminded me, I guess I will go through them again. :smiley:

**Pull request merged**
