### PR TITLE
added kukri

### PR DESCRIPTION
**Pull request by jurajkulich**

### CODE REVIEW

**Comment by doficia** [comment]
Hi @yuro8! Sorry but there are some issues. The kukri has a huge palette, is not really pixel art and there are lots of half-transparent pixels. The mining helmet is OK, but is not the right size for icons. May I ask if they are original works?

**Comment by jurajkulich** [comment]
Oh sorry, I don't know why I thought the size is 180x180. I can update it to 128x128 of course. Yes, the are originals

**Comment by doficia** [comment]
Thanks @yuro8! That would be great. I can accept the Kukri then. :smiley:

**Comment by jurajkulich** [comment]
@doficia I try to make the kukri better too :D hope it will be here in the evening

**Comment by doficia** [comment]
OK, thank you. :smiley:

**Comment by jurajkulich** [comment]
@doficia Hopefully it's correct now :D.

**Comment by doficia** [comment]
Thank you! Do you want to put the Mining Helmet in this PR or should I accept? :smiley:

**Comment by jurajkulich** [comment]
You can accept. Thank you :blush:

**Comment by doficia** [comment]
I was blind and did not see the Mining Helmet... thanks again. :smiley:

**Pull request merged**
