### PR TITLE
ice axe sprite added

### PR DESCRIPTION
**Pull request by sinAshish**

### CODE REVIEW

**Comment by doficia** [comment]
Hi @sinAshish! The sprite looks great, but it does not comply with the style rules. There should be no transparent pixels, and it resembles photorealism more than pixel art. Could you please go through CONTRIBUTING.md and some example sprites again? :smiley:

**Comment by sinAshish** [comment]
ok I'll try to submit another one by tonight. 😃

**Comment by doficia** [comment]
Thank you. Sorry for the trouble. :smiley:

**Comment by sinAshish** [comment]
can you elaborate a bit on transparent pixels and photorealism and how to remove them? :/ Noob here. Doing a sprite for the first time.

**Comment by doficia** [comment]
Hey, no worries. In pixel art you create a brand new image from scratch with a dedicated app. Piskel is great, it is online and specifically made for pixel art.

You place every pixel by hand to draw the object. It will not be photorealistic. That happens when you modify and existing real photo of an object. It will be blurred, have huge palettes, etc.

To avoid transparency, simply don't put transparent pixels. :smiley: It is also a side effect of working with real photos or vector graphics (or using a brush in some image editors, they draw smoothly by adding lots of transparent, anti-aliased pixels).

Sorry, I am not the best at explaining stuff. My suggestion is to watch a video on YouTube, something like 'pixel art timelapse' so you see the process in motion. :smiley:

**Comment by sinAshish** [comment]
katana and javelin added. need some time to perfect ice axe 😄

**Comment by doficia** [comment]
Hi @sinAshish! They are nice. :) I'll leave the PR open till the Ice Axe, is that fine by you?

**Comment by sinAshish** [comment]
add the other two if you would. I think the ice axe will take some time. I will make a separate PR for it if it's fine.

**Pull request merged**
